### ISSUE TITLE
`vagrant up` fails in parallel mode

### ISSUE THREAD

**Issue by bechtoldt** [displague/vagrant-linode#34]
I'm trying to deploy 20 Vagrant VMs at the same time and getting the following error.

```
vagrant up --provider=linode --parallel
```

```
An unexpected error occurred when executing the action on the
'client20' machine. Please report this as a bug:

undefined method `find' for nil:NilClass

/Users/arnoldbechtoldt/.vagrant.d/gems/gems/vagrant-linode-0.1.1/lib/vagrant-linode/actions/create.rb:43:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

~ 10 VM deployments fail with this error. deploying only 10 VMs (instead of 20) at the same time works without any problems.

**Comment by levlaz** [comment]
Hi Arnold,

Can you open a support ticket with Linode and ask them what your "thing limit" is? By default it's fairly low (around 20) so you may be running out of instances and the plugin may not know how to handle that. 

You can ask the support team to raise the limit for you. I have a suspicion that this is likely the issue.

Best,
Lev

**Comment by displague** [comment]
@levlaz makes a good point, but vagrant-linode should handle this condition better and let you know that you hit the thing limit if that is the case.

**Comment by bechtoldt** [comment]
Thanks for the tip! I've opened a ticket (4768646).

**Comment by levlaz** [comment]
@bechtoldt I updated the ticket, let me know if it works. 

@displague Do you know if vagrant-linode has logic for this? If not we should add it. :)

**Comment by bechtoldt** [comment]
@levlaz 

I'm still getting the same error. (see above)

```
==> client16: An error occurred. The error will be shown after all tasks complete.
==> client14: An error occurred. The error will be shown after all tasks complete.
==> client17: An error occurred. The error will be shown after all tasks complete.
==> client1: An error occurred. The error will be shown after all tasks complete.
==> client5: An error occurred. The error will be shown after all tasks complete.
==> client6: An error occurred. The error will be shown after all tasks complete.
==> client3: An error occurred. The error will be shown after all tasks complete.
==> client20: An error occurred. The error will be shown after all tasks complete.
```

**Comment by displague** [comment]
I think the box state may be off from the error you encountered.  --parallel works when you don't encounter the thinglimit problem.

```
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	(1..4).each do |i|
		['dev','prod'].each do |linode_env|
			config.vm.define "#{linode_env}#{i}" do |linode|
				linode.vm.synced_folder ".", "/vagrant", rsync__exclude: [".git/",'vendor/'], type: 'rsync'
				linode.vm.hostname = "#{linode_env}#{i}"
				linode.vm.provider :linode do |provider, override|
					override.ssh.private_key_path = '~/.ssh/id_rsa'
					override.vm.box = "linode"
					override.vm.box_url = "https://github.com/displague/vagrant-linode/raw/master/box/linode.box"
					provider.kernel = '4.1.0'
					provider.label = linode.vm.hostname
					provider.token = ENV['LINODE_API_KEY']
					provider.datacenter = 'newark'
					provider.plan = 'Linode 1024'
					provider.distribution = 'Debian 8'
				end
			end
		end
	end
end
```

```
~src/test-vagrant-linode $ vagrant up --provider=linode --parallel
Bringing machine 'dev1' up with 'linode' provider...
Bringing machine 'prod1' up with 'linode' provider...
Bringing machine 'dev2' up with 'linode' provider...
Bringing machine 'prod2' up with 'linode' provider...
Bringing machine 'dev3' up with 'linode' provider...
Bringing machine 'prod3' up with 'linode' provider...
Bringing machine 'dev4' up with 'linode' provider...
Bringing machine 'prod4' up with 'linode' provider...
==> dev3: Creating a new linode...
==> prod4: Creating a new linode...
==> dev2: Creating a new linode...
==> prod3: Creating a new linode...
==> prod1: Creating a new linode...
==> prod2: Creating a new linode...
==> dev4: Creating a new linode...
==> dev1: Creating a new linode...
==> dev3: Created a new linode... 1125419
==> dev3: Booting Linode 1125419 ...
==> dev1: Created a new linode... 1125420
==> dev3: Assigned IP address: 45.79.131.199
==> dev1: Booting Linode 1125420 ...
==> prod2: Created a new linode... 1125421
==> dev1: Assigned IP address: 45.79.139.194
==> prod2: Booting Linode 1125421 ...
==> prod2: Assigned IP address: 45.79.147.191
==> prod4: Created a new linode... 1125423
==> prod4: Booting Linode 1125423 ...
==> prod1: Created a new linode... 1125424
==> prod4: Assigned IP address: 45.79.130.189
==> prod1: Booting Linode 1125424 ...
==> prod3: Created a new linode... 1125425
==> dev2: Created a new linode... 1125426
==> prod1: Assigned IP address: 45.79.133.188
==> dev4: Created a new linode... 1125427
==> prod3: Booting Linode 1125425 ...
==> dev2: Booting Linode 1125426 ...
==> dev4: Booting Linode 1125427 ...
==> prod3: Assigned IP address: 45.79.141.188
==> dev2: Assigned IP address: 45.79.137.205
==> dev4: Assigned IP address: 45.79.132.195
==> dev1: Modifying hostname: dev1...
==> dev3: Modifying hostname: dev3...
==> prod4: Modifying hostname: prod4...
==> prod2: Modifying hostname: prod2...
==> prod3: Modifying hostname: prod3...
==> prod1: Modifying hostname: prod1...
==> dev4: Modifying hostname: dev4...
==> dev2: Modifying hostname: dev2...
```

```
vagrant provision
==> dev1: Rsyncing folder: ~/src/test-vagrant-linode/ => /vagrant...
==> prod1: Rsyncing folder: ~/src/test-vagrant-linode/ => /vagrant...
==> dev2: Rsyncing folder: ~/src/test-vagrant-linode/ => /vagrant...
==> prod2: Rsyncing folder: ~/src/test-vagrant-linode/ => /vagrant...
==> dev3: Rsyncing folder: ~/src/test-vagrant-linode/ => /vagrant...
==> prod3: Rsyncing folder: ~/src/test-vagrant-linode/ => /vagrant...
==> dev4: Rsyncing folder: ~/src/test-vagrant-linode/ => /vagrant...
==> prod4: Rsyncing folder: ~/src/test-vagrant-linode/ => /vagrant...
```

**Comment by bechtoldt** [comment]
I'm not hitting the thinglimit anymore. Are you able to deploy ~ 20 VMs at the same time?

**Comment by displague** [comment]
When a thing limit is encountered, you will see this:

```
An unexpected error occurred when executing the action on the
'prod2-fremont' machine. Please report this as a bug:

API Error on linode.create: [{"ERRORCODE"=>15, "ERRORMESSAGE"=>"Account Limit reached. Please open a support ticket."}]

/Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:85:in `parse'
/Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:79:in `error_check'
/Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:71:in `call'
/Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:62:in `block in make_call'
/Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:63:in `make_call'
/Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:44:in `method_missing'
/Users/marques/.vagrant.d/gems/gems/vagrant-linode-0.1.2/lib/vagrant-linode/actions/create.rb:76:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

The vagrant'ing will continue for any Linodes that were created before the limit was encountered.

**Comment by displague** [comment]
@bechtold if you aren't too attached to those Linodes, would you mind destroying them using `vagrant destroy the_name` and trying again?

**Comment by bechtoldt** [comment]
@displague 

I get some HTTP 503 errors. Maybe because vagrant fires all API requests against the linode API servers at the same time..

debug log: https://np.adm.sx/view/5b29487d

**Comment by displague** [comment]
Fog adds a delay between commands.  I believe we will need to add the same to avoid triggering the apparent rate limits.

**Comment by displague** [comment]
I'm closing this to deal with the more succinct rate limiting issue. https://github.com/displague/vagrant-linode/issues/18
