### ISSUE TITLE
Incompatibility JSON 1.8.3

### ISSUE THREAD

**Issue by fringerdarlinger** [displague/vagrant-linode#59]
Hi there,

Recently updated and got this:
/Users/jdfriedrikson/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext.rb:13:in `require': incompatible library version - /Users/jdfriedrikson/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext/parser.bundle (fatal)
        from /Users/jdfriedrikson/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext.rb:13:in `<module:Ext>'
        from /Users/jdfriedrikson/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext.rb:12:in `<module:JSON>'
        from /Users/jdfriedrikson/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext.rb:9:in `<top (required)>'
        from /Users/jdfriedrikson/.vagrant.d/gems/gems/json-1.8.3/lib/json.rb:58:in `require'
        from /Users/jdfriedrikson/.vagrant.d/gems/gems/json-1.8.3/lib/json.rb:58:in `<module:JSON>'
        from /Users/jdfriedrikson/.vagrant.d/gems/gems/json-1.8.3/lib/json.rb:54:in `<top (required)>'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant.rb:55:in `require'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant.rb:55:in `<top (required)>'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:105:in `require'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:105:in `<main>'

Would this be a trivial thing to fix?

**Comment by fringerdarlinger** [comment]
Blah. Please ignore this. This is an issue with Vagrant and not Vagrant Linode.
