### ISSUE TITLE
plugin installation fails - `check_version_conflict'

### ISSUE THREAD

**Issue by cswarth** [displague/vagrant-linode#68]
Can anyone help me get around this installation error?
I'm on macOS Sierra 10.12.1 with `ruby` installed via `brew`.
I can't even see where json-1.8.1 might be installed.

```
$ vagrant plugin install --verbose vagrant-linode
Installing the 'vagrant-linode' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate json-1.8.3, already activated json-1.8.1 (Gem::LoadError)
        from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1276:in `activate'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:319:in `block in activate_solution'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:316:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:316:in `activate_solution'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:244:in `internal_install'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:97:in `install'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:192:in `verbose'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/plugin/manager.rb:70:in `install_plugin'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/action/install_gem.rb:37:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/base.rb:14:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/install.rb:32:in `block in execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/install.rb:31:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/install.rb:31:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/root.rb:66:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/cli.rb:42:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/environment.rb:308:in `cli'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/bin/vagrant:123:in `<main>'
```

```
$ vagrant --version
Vagrant 1.9.0
$ ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
$ gem list | grep -i json
json (1.8.3)
```

**Comment by cmarzullo** [comment]
just ran into this also. seems like vagrant dropped the json gem to 1.8.1. in version 1.9.0

```
[c@mac opt]$ vagrant version
Installed Version: 1.9.0
Latest Version: 1.9.0

[c@mac opt]$ find . -iname json\* | grep gemspec
./vagrant/embedded/lib/ruby/gems/2.2.0/specifications/default/json-1.8.1.gemspec
```

**Comment by anthonymf** [comment]
Confirmed in vagrant 1.9.1 and 1.9.0.
Reverting to vagrant 1.8.7 resolved this for me.

I can't find this reported as an issue for vagrant itself.  But the underlying issue could relate to the 1.9.0 bundler changes here
https://github.com/mitchellh/vagrant/pull/7793
https://github.com/mitchellh/vagrant/pull/8011
https://github.com/mitchellh/vagrant/pull/8000
https://github.com/mitchellh/vagrant/pull/8031

**Comment by cswarth** [comment]
Looks like this might have been fixed in the repo?
https://github.com/displague/vagrant-linode/commit/f6888716766b50359369356483b8f7ae2c2012f2

**Comment by displague** [comment]
I pushed that change out there for some testing - I haven't published the change yet because I ran into bundler 1.12 vs 1.13 problems.

**Comment by Qtrain** [comment]
Running into this issue as well. pls2publish 👍

**Comment by displague** [comment]
Published v0.2.8 with the removal of the `json` dependency.

**Comment by cswarth** [comment]
FWIW, the linode plugin installs fine after upgrading to [Vagrant 1.9.1](https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1.dmg).
The [vmware plugin](https://www.vagrantup.com/docs/vmware/installation.html) also failed to install in vagrant 1.9.0 but does install under Vagrant 1.9.1.

Maybe HashiCorp just released a bogus release that had some problems?

```
$ vagrant --version
Vagrant 1.9.1

$ vagrant plugin install vagrant-linode
Installing the 'vagrant-linode' plugin. This can take a few minutes...
Fetching: multi_xml-0.6.0.gem (100%)
Fetching: httparty-0.13.7.gem (100%)
When you HTTParty, you must party hard!
Fetching: linodeapi-1.0.1.gem (100%)
Fetching: vagrant-linode-0.2.8.gem (100%)
```

If other can confirm, this issue can be closed....

**Comment by anthonymf** [comment]
Now installs fine for me on mac

```
MacBook-Pro-2: anthony$ vagrant --version
Vagrant 1.9.1
MacBook-Pro-2: anthony$ vagrant plugin install vagrant-linode
Installing the 'vagrant-linode' plugin. This can take a few minutes...
Fetching: multi_xml-0.6.0.gem (100%)
Fetching: httparty-0.13.7.gem (100%)
When you HTTParty, you must party hard!
Fetching: micromachine-2.0.0.gem (100%)
Fetching: linodeapi-1.0.1.gem (100%)
Fetching: vagrant-vbguest-0.13.0.gem (100%)
Fetching: vagrant-linode-0.2.8.gem (100%)
Installed the plugin 'vagrant-linode (0.2.8)'!
```

**Comment by displague** [comment]
Looks to be resolved.  Thanks.
