### ISSUE TITLE
.vagrant.d/gems/2.2.5/gems/vagrant-linode-0.2.8/lib/vagrant-linode/actions/create.rb:246:in `block in call': not ready (RuntimeError)

### ISSUE THREAD

**Issue by nodje** [displague/vagrant-linode#73]
I can't get past the init phase with the Vagrant-linode plugin, it seems to never detect the machine is ready. `VAGRANT_LOG=debug` doesn't give more info on what's going on.

Here's my Vagrant config:
```
# Linode
  config.vm.provider :linode do |provider, override|
    override.ssh.private_key_path = "metadata/.ssh/id_rsa"
    override.ssh.username = "root"
    override.vm.box = "linode/ubuntu1404"
    #provider.ssh_key_name = "root"
    #provider.setup = false
    provider.api_key = "mytoken"
    provider.distribution = "Ubuntu 14.04 LTS"
    provider.datacenter = "frankfurt"
    provider.plan = "Linode 1024"
    provider.label = "Ansible_test"
  end
```
Here's the stacktrace 
```
vagrant destroy -f && vagrant up --provider=linode                                            
==> default: VM not created. Moving on...
Bringing machine 'default' up with 'linode' provider...
==> default: Linode has not been created
==> default: Creating a new linode...
==> default: Created a new linode... 3118946, https://manager.linode.com/linodes/dashboard/Ansible_test
==> default: Booting Linode 3118946 ...
==> default: Assigned IP address: 172.104.150.172
==> default: Machine State ID: brand_new
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: brand_new
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
==> default: Machine State ID: active
==> default: IP Address: 172.104.150.172
/Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-linode-0.2.8/lib/vagrant-linode/actions/create.rb:246:in `block in call': not ready (RuntimeError)
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/util/retryable.rb:17:in `retryable'
        from /Users/jean/.vagrant.d/gems/2.2.5/gems/vagrant-linode-0.2.8/lib/vagrant-linode/actions/create.rb:244:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
        from /Users/jean/.vagrant.d/gems/2.2.5/gems/vagrant-linode-0.2.8/lib/vagrant-linode/actions/connect_linode.rb:31:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
        from /Users/jean/.vagrant.d/gems/2.2.5/gems/vagrant-linode-0.2.8/lib/vagrant-linode/actions/message_not_created.rb:11:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builtin/provision.rb:80:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/machine.rb:225:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/machine.rb:200:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/environment.rb:567:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/machine.rb:186:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/machine.rb:186:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

```
I can ssh to the created instance with `ssh -i metadata/.ssh/id_rsa root@172.104.150.172`

**Comment by displague** [comment]
Can you try reproducting this in 0.3.0 and if so, does the problem exist when using the default key path? `~/.ssh/id_rsa` ?
