### ISSUE TITLE
does not handle network failures gracefully

### ISSUE THREAD

**Issue by displague** [displague/vagrant-linode#8]
During an API server hick-up, I received the following stack after a long delay:
```
displague@Inspiron-560:~/src/vagrant-linode$ bundle exec vagrant destroy
Your Gemfile lists the gem vagrant-linode (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Vagrant appears to be running in a Bundler environment. Your
existing Gemfile will be used. Vagrant will not auto-load any plugins
installed with `vagrant plugin`. Vagrant will autoload any plugins in
the 'plugins' group in your Gemfile. You can force Vagrant to take over
with VAGRANT_FORCE_BUNDLER.

You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

/usr/lib/ruby/2.1.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
	from /usr/lib/ruby/2.1.0/net/protocol.rb:152:in `rbuf_fill'
	from /usr/lib/ruby/2.1.0/net/protocol.rb:134:in `readuntil'
	from /usr/lib/ruby/2.1.0/net/protocol.rb:144:in `readline'
	from /usr/lib/ruby/2.1.0/net/http/response.rb:39:in `read_status_line'
	from /usr/lib/ruby/2.1.0/net/http/response.rb:28:in `read_new'
	from /usr/lib/ruby/2.1.0/net/http.rb:1408:in `block in transport_request'
	from /usr/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
	from /usr/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
	from /usr/lib/ruby/2.1.0/net/http.rb:1378:in `request'
	from /usr/lib/ruby/2.1.0/net/http.rb:1371:in `block in request'
	from /usr/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from /usr/lib/ruby/2.1.0/net/http.rb:1369:in `request'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/gems/httparty-0.13.1/lib/httparty/request.rb:93:in `perform'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/gems/httparty-0.13.1/lib/httparty.rb:521:in `perform_request'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/gems/httparty-0.13.1/lib/httparty.rb:473:in `post'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/gems/httparty-0.13.1/lib/httparty.rb:563:in `post'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/gems/linode-0.8.1/lib/linode.rb:96:in `post'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/gems/linode-0.8.1/lib/linode.rb:81:in `send_request'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/gems/linode-0.8.1/lib/linode.rb:15:in `block (2 levels) in has_method'
	from /home/displague/src/vagrant-linode/lib/vagrant-linode/provider.rb:14:in `linode'
	from /home/displague/src/vagrant-linode/lib/vagrant-linode/provider.rb:98:in `state'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/machine.rb:432:in `state'
	from /home/displague/src/vagrant-linode/lib/vagrant-linode/actions/check_state.rb:12:in `call'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/action/warden.rb:34:in `call'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/action/builder.rb:116:in `call'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/action/runner.rb:66:in `block in run'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/util/busy.rb:19:in `busy'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/action/runner.rb:66:in `run'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/action/builtin/call.rb:43:in `call'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/action/warden.rb:34:in `call'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/action/warden.rb:34:in `call'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/action/builder.rb:116:in `call'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/action/runner.rb:66:in `block in run'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/util/busy.rb:19:in `busy'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/action/runner.rb:66:in `run'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/machine.rb:196:in `action_raw'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/machine.rb:173:in `block in action'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/environment.rb:434:in `lock'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/machine.rb:161:in `call'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/machine.rb:161:in `action'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/plugins/commands/destroy/command.rb:31:in `block in execute'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/plugin/v2/command.rb:220:in `each'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/plugins/commands/destroy/command.rb:30:in `execute'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/cli.rb:42:in `execute'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/lib/vagrant/environment.rb:252:in `cli'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bundler/gems/vagrant-85d63a91f7af/bin/vagrant:166:in `<top (required)>'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bin/vagrant:23:in `load'
	from /home/displague/src/vagrant-linode/vendor/bundle/ruby/2.1.0/bin/vagrant:23:in `<main>'
```

**Comment by displague** [comment]
This is a dupe of https://github.com/displague/vagrant-linode/issues/18.  Bye.
