### ISSUE TITLE
Cannot run vagrant up

### ISSUE THREAD

**Issue by numediaweb** [displague/vagrant-linode#86]
Whenever I issue this command:
```
vagrant up --provider=linode  
```
I get an error:
```
FO machine:   - Box:
 INFO machine:   - Data dir: D:/apps/vagrant-linode/.vagrant/machines/default/linode
 INFO machine: Calling action: read_state on provider Linode (new)
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-d8f066b9cb89bcf1646adf17a1656ba1
 INFO interface: Machine: action ["read_state", "start", {:target=>:default}]
 INFO host: Autodetecting host type for [#<Vagrant::Environment: D:/apps/vagrant-linode>]
 INFO host: Detected: windows!
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: machine_action_read_state #<Vagrant::Action::Builder:0x000000059d5850>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x000000058d3038>
 INFO warden: Calling IN action: #<VagrantPlugins::Linode::Actions::ConnectLinode:0x000000058d3010>
 INFO connect_linode: Connecting to Linode api_url...
 INFO warden: Calling IN action: #<VagrantPlugins::Linode::Actions::ReadState:0x000000058af098>
 INFO read_state: Machine state is 'not_created'
 INFO warden: Calling OUT action: #<VagrantPlugins::Linode::Actions::ReadState:0x000000058af098>
 INFO warden: Calling OUT action: #<VagrantPlugins::Linode::Actions::ConnectLinode:0x000000058d3010>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x000000058d3038>
 INFO interface: Machine: action ["read_state", "end", {:target=>:default}]
 INFO environment: Released process lock: machine-action-d8f066b9cb89bcf1646adf17a1656ba1
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO machine: New machine ID: nil
 INFO interface: Machine: metadata ["provider", :linode, {:target=>:default}]
...
==> default: Linode has not been created
...
/.vagrant.d/gems/2.3.4/gems/linodeapi-2.0.1/lib/linodeapi/helpers.rb:23:in `parse': API Error encountered (LinodeAPI::APIError)
        from C:/Users/aidrissi/.vagrant.d/gems/2.3.4/gems/linodeapi-2.0.1/lib/linodeapi/helpers.rb:10:in `error_check'

```

**Comment by numediaweb** [comment]
The issue was with using `api_key` instead of the working `token`.
